# Variables in sway
#
# This file must be read first for other config files to function properly!
#
#
# Application launcher
#
    # Requires: sudo apt install fuzzel
    set $menu fuzzel
#
# Home row direction keys, like vim
#
    set $left h
    set $down j
    set $up k
    set $right l
#
# Mod key
#
    set $mod Mod4
#
# Terminal emulator
#
    # Requires: sudo apt install foot
    set $term foot