# Custom keybindings
#
#
# Audio configuration
# 
    # Create custom keys for volume control
    bindsym $mod+z exec pactl set-sink-volume @DEFAULT_SINK@ -5%
    bindsym $mod+x exec pactl set-sink-volume @DEFAULT_SINK@ +5%

    # [How can I set up keybindings with Sway for volume control?](https://www.reddit.com/r/swaywm/comments/qei3oh/how_can_i_set_up_keybindgs_with_sway_for_volume/)
#    
# Container focus
#
    # Move focus to the child container
    bindsym $mod+Shift+a focus child
#
# Power profiles daemon configuration
#
    # Changes are visible in waybar "power-profiles-daemon" module

    # Requires: sudo apt install power-profiles-daemon
    # Use toggle to switch between three profiles power-saver, balanced and performance
    # bindsym $mod+alt+p exec $HOME/dotfiles/sway/sway-scripts/toggle_power_profile_ppd.sh

    # Requires: sudo apt install tuned
    # Use toggle to switch between three profiles powersave, balanced and throughput-performance
    bindsym $mod+alt+p exec $HOME/dotfiles/sway/sway-scripts/toggle_power_profile_tuned.sh
#
# Poweroff configuration
#
    # Create custom keys for system poweroff
    bindsym $mod+shift+backspace exec "sync && systemctl poweroff"
#
# Restart / Exit
#
    # Requires: sudo apt install fuzzel
    # exit sway with script copied from EndeavourOS Sway Community Edition
    bindsym $mod+shift+e exec $HOME/dotfiles/sway/sway-scripts/power_menu.sh
#
# Scratchpad
#
    # Move the currently focused window to the scratchpad
    bindsym $mod+Shift+minus move scratchpad

    # Show the next scratchpad window or hide the focused scratchpad window.
    bindsym $mod+minus scratchpad show
#
# Swaylock configuration
#
    # Create custom key for locking screen
    bindsym $mod+alt+l exec swaylock
#
# Switch workspaces
#
    # Quickly toggle 'back and forth' between current and last workspace
    bindsym $mod+Tab workspace back_and_forth

    # Switch to prev/next workspace on CURRENT output
    bindsym $mod+n workspace next_on_output
    bindsym $mod+p workspace prev_on_output

    # Switch to prev/next workspace on ALL outputs
    bindsym $mod+Shift+n workspace next
    bindsym $mod+Shift+p workspace prev

    # [switch between current and last workspace keybinding](https://www.reddit.com/r/swaywm/comments/qv548y/comment/hkudutl/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1)
#
# Switch dark/light theme
#
    # Toggle between light and dark theme
    bindsym $mod+shift+t exec sh -c 'CURRENT=$(gsettings get org.gnome.desktop.interface color-scheme); if echo "$CURRENT" | grep -q dark; then gsettings set org.gnome.desktop.interface color-scheme "prefer-light"; else gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"; fi'
#
# Toggle laptop screen (internal display)
#
    # turn on/off internal display with toggle
    bindsym $mod+shift+d output eDP-1 toggle
#
# Toggle waybar
#
    # show/hide waybar
    bindsym $mod+o exec killall -SIGUSR1 waybar
