# Input devices configuration
#
# Note: Use "input * { } wildcard", instead of hardcoded identifiers
#
#
# Enable laptop touchpad functionality
#
    input * {
        # Enable tap to click
        tap enabled

        # Disable acceleration
        accel_profile flat
    }
#
# Change keyboard language layout
#
    input * {
        # change input layout, first one is the default
        xkb_layout us,de

        # Use shift+alt as toggle
        xkb_options grp:alt_shift_toggle
    }
#
# Change repeat delay/rate of keyboard
#
    #input * {
    #    # default values in sway are 600/25 (delay/rate)
    #    repeat_delay 600
    #    repeat_rate 25
    #}

    # Check values with $ swaymsg -t get_inputs | less
    # and search for /repeat
    # https://man.archlinux.org/man/sway-input.5