# Appearance and layout
#
# Window border behavior
#
    # If enabled, borders are not shown when the window is the only one in a workspace
    smart_borders on

    # Set the border thickness AND hide the title bar of windows
    # Note: disables the ability to drag with mouse via titlebar, use $mod with mouse instead
    default_border pixel 6
#
# Window border colors
#
    # CLASS                 BORDER   BACKGROUND    TEXT   INDICATOR   CHILD_BORDER

    # Use magenta border on focused window for best visibility
    #client.focused          #4c7899  #285577    #ffffff  #2e9ef4   #285577
    client.focused          #4c7899  #285577    #ffffff  #2e9ef4   #ff00ff

    # [How to remove borders of unfocused windows](https://www.reddit.com/r/swaywm/comments/14iopxp/how_to_remove_borders_of_unfocused_windows/)
    set $clear #ffffff00
    #client.focused_inactive  #333333  #5f676a     #ffffff  #484e50    $clear
    #client.unfocused         #333333  #222222     #888888  #292d2e    $clear

    # Use dark borders instead of clear borders on inactive/unfocused windows
    client.focused_inactive  #333333  #5f676a     #ffffff  #484e50    #000000
    client.unfocused         #333333  #222222     #888888  #292d2e    #000000
#
# Default workspace layout
#
    # Tabbed view allows only one full screen window per screen
    workspace_layout tabbed
#
# Desktop background
#
    # Use light background for desktop
    # Note: lock screen background is managed separately in swaylock config
    output * bg /usr/share/backgrounds/default.jxl fill