# default values (commented out) are in /etc/xdg/foot/foot.ini
# https://man.archlinux.org/man/foot.ini.5.en

# Set default font and fallback fonts for e.g. ~/.config/waybar/config.jsconc
#font=GeistMono Nerd Font Propo:size=14, Font Awesome 7 Free Solid, Font Awesome 7 Brands

# monospace meaning: “Ask the system for the default monospace font.”
# check what monospace resolves to with `fc-match monospace`
font=monospace:size=14
